### ISSUE TITLE
TypeError The "listener" argument must be of type function. Received an instance of Object

### ISSUE THREAD

**Issue by Deep-Codes** [Yimura/Scraper#3]
**Describe the bug**

This issue comes when I am using Electron With React TypeScript Webpack and Electron. It works like charm in Separate Node.js Application.

**To Reproduce**
1. Clone [this repo.](https://github.com/electron-react-boilerplate/electron-react-boilerplate
2. `yarn add @yimura/scraper`
3. Type the following:

 ```js 
import youtube from '@yimura/scraper'

const yt = new youtube.default();
yt.search('Never gonna give you up').then(results => {
    console.log(results[0]);
});
```

4. `yarn start` and you should see the error in Electron.

**Expected behavior**
Should Print the JSON data for the YT query.

**Screenshots**
<img width="1025" alt="Screenshot 2021-02-15 at 7 11 39 PM" src="https://user-images.githubusercontent.com/61158210/107953800-a4409800-6fc1-11eb-9398-e6c8b14dfe82.png">

**Comment by Deep-Codes** [comment]
Seems to be an issue with `HTTPS` module

**Comment by Yimura** [comment]
Thanks for taking the time to create this issue, I'll take a look at later today.

**Comment by Yimura** [comment]
May I ask what environment you have to develop this application?
OS: 
Node: 

Whatever other things come to your head.

**Comment by Deep-Codes** [comment]
> May I ask what environment you have to develop this application?
> OS:
> Node:
> 
> Whatever other things come to your head.

Sure thing!

OS: MacOS Catalina 10.15.7
Node: v15.8.0
Electron:  v11.0.1

**Comment by Yimura** [comment]
I've looked over your issue and it seems that your environment is configured incorrectly.
Take a better look at how you structure your code.

I don't use typescript so I won't be able to help you further.

**Comment by Deep-Codes** [comment]
Don't think it's an issue with the Environment.

Anyway Thanks 👍🏽 .

**Comment by Yimura** [comment]
I really wish to help you but the issue does not appear to be with this package, sorry.

**Comment by GeopJr** [comment]
@Deep-Codes scraper cannot run inside a jsx/tsx file. However it runs just as intended  inside a ts/js file! Like `menu.ts` in the repo you mentioned. If you want to use it with your app, your best solution would be to just pass the result to your tsx/jsx from a js/ts.

**Comment by Deep-Codes** [comment]
@GeopJr Yeah Probably should create an `exec` child process instead Seems to be working for now✨ :)

@Yimura I totally get it,  this Library is Fantastic btw!

Have a Great Day Everyone🎉
