### ISSUE TITLE
Thumbnail scrape issues

### ISSUE THREAD

**Issue by erturkgg** [Yimura/Scraper#7]
Scraper is working really good but there is an issue with thumbnail sizes. 
Let me show the issue:

Normal thumbnail from YouTube Search:
![image](https://user-images.githubusercontent.com/59501147/119377434-caaf5700-bcc5-11eb-91a0-9987ba5c8ab9.png)

Oversized thumbnail from Yimura Scraper:
![image](https://user-images.githubusercontent.com/59501147/119377553-f16d8d80-bcc5-11eb-94d5-7e64540be389.png)

Did you see the black bars? It is the issue.

**Comment by GeopJr** [comment]
For a temp solution till my PR gets reviewed, you can do the following:
`'https://i.ytimg.com/vi/'+ videoId +'/maxresdefault.jpg'`
(replace videoId with the id returned from scrapper)

**Comment by Yimura** [comment]
Thanks for the fix @GeopJr , I have merged the changes into master, I'll publish this fix to npmjs when I get back to my pc.

**Comment by Yimura** [comment]
I have published the changes to npmjs, thanks for your report @erturkgg
