### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by erturkgg** [Yimura/Scraper#9]
![Screenshot_3](https://user-images.githubusercontent.com/59501147/122751231-286c9a00-d298-11eb-86bf-a366a5bea00a.png)

I'm having this issue rn, do you know how to fix?

**Comment by GeopJr** [comment]
Hello!
Could you tell me the node version you are using?
(`node -v`)

Edit:
For future reference, optional chaining (?.) is available on node >= 14 and all browsers minus IE.

(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by erturkgg** [comment]
> Hello!
> Could you tell me the node version you are using?
> (`node -v`)

Updated node to v14 and did npm audit fix and fixed.
